services:
  pelican:
    build: 
      context: .  # Use the entire repo as context
      dockerfile: pelican/Dockerfile
  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile
    depends_on: 
      - pelican
  pigeon:
    build: 
      context: .
      dockerfile: pigeon/Dockerfile
  parrot:
    build: 
      context: .
      dockerfile: parrot/Dockerfile
    depends_on: 
      - pigeon
  owl:
    build:
      context: .
      dockerfile: owl/Dockerfile
