services:
  pelican:
    build: 
      context:    ./pelican
      dockerfile: Dockerfile
  simulator:
    build:
      context:    ./simulator
      dockerfile: Dockerfile
    depends_on: 
      - pelican
