services:
  pelican:
    build: 
      context:    ./pelican
      dockerfile: Dockerfile
  simulator:
    build:
      context:    ./simulator
      dockerfile: Dockerfile
    depends_on: 
      - pelican
  pigeon:
    build: 
      context:    ./pigeon
      dockerfile: Dockerfile
  parrot:
    build: 
      context:    ./parrot
      dockerfile: Dockerfile
    depends_on: 
      - pigeon
